version: "2"

services:
  minio:
    image: "bitnami/minio:latest"
    platform: linux/amd64
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    volumes:
      - ./minio/data:/data
